### PR TITLE
Replace Travis by Github Actions

### PR DESCRIPTION
**Pull request by thomasperrot**
Cf. #85 

### Successful PR Checklist:
- [ ] Tests
- [ ] Documentation (optionally: [run spell checking](https://github.com/peopledoc/septentrion/blob/master/CONTRIBUTING.rst#build-the-documentation))
- [X] Had a good time contributing? (feel free to give some feedback)

### CODE REVIEW

**Review by ewjoachim — APPROVED** [review]
You'll need @mgu 's help to push

**Comment by ewjoachim** [comment]
(@thomasperrot can you rebase to fix the CI ?)

**Comment by thomasperrot** [comment]
@ewjoachim to push to codecov ? 

I rebased after my other PR has been merge. However their are still some troubles in the documentation (lines too long...). In my other PR I only checked that the doc could be built, without checking linting, my bad...
I'll open a new one to fix doc linting before merging this one.

**Comment by ewjoachim** [comment]
Ah ok

**Comment by elemoine** [comment]
Thanks for that @thomasperrot!

**Pull request merged**
