### PR TITLE
Rename to septentrion

### PR DESCRIPTION
**Pull request by alexdashkov**
It's a PR for renaming `west` into `septentrion`. 
TODO:
- [x] Rename all the code parts;
- [x] fix tests and linters;
- [x] rename repo;
- [x] change CI conf (codecov and travis);

### CODE REVIEW

**Comment by k4nar** [comment]
Just for the records, I'm not a huge fan of the name `septentrion`. This is a long and non-english word which will be very hard to remember & type for non (old) french speakers.

But I don't have any better name, and I agree that this is a cool word out of this context :) . So LGTM.

**Comment by alexdashkov** [comment]
@k4nar I agree with you, really you've described my situation :D However, I believe that this name will be hardcoded in the scripts (Docker build/deploy to integration etc) so I don't think we should memorize it.

**Comment by k4nar** [comment]
Yeah I'm not worried for its usage at PeopleDoc, more for the day when we'll want to share it to the world.

**Comment by ewjoachim** [comment]
Septentrion is an english word https://en.wiktionary.org/wiki/septentrion (probably not used in English more that it's used in French, though)

**Comment by k4nar** [comment]
> obsolete, obs.
    No longer in use, and (of a term) no longer likely to be understood. Obsolete is a stronger term than archaic, and a much stronger term than dated. See Wiktionary:Obsolete and archaic terms.

:smile:

**Comment by mgu** [comment]
That's good ! Nobody will steal the name :smile:

**Pull request merged**
